# Generated by Django 3.2.6 on 2022-05-30 00:47

from django.db import migrations, models
import sympycharfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SympyCharFieldTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', sympycharfield.models.SympyCharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
